apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: flux-system
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      nodePort: 33333
      protocol: TCP
      targetPort: http
    - nodePort: 33334
      targetPort: grpc
      protocol: TCP
      name: grpc
  type: NodePort
